config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'
  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # Needed to instantiate the form_for
  end

  def create
    @task = Task.new(task_params)
    @task.save # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])

  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
<h1>Edit task</h1>
<div class="todo">
<%= form_for(@task) do |f| %>
 <div class="form"> <%= f.label :title %>
  <%= f.text_field :title %></div>
  <div class="form"><%= f.label :details %>
  <%= f.text_field :details %></div>
  <div class="check"><%= f.check_box :completed %>
  <%= f.label :completed %></div>
  <div class="sub"><%= f.submit %></div>
<% end %>
</div>
<hr>
<%= link_to tasks_path do %>
  <div class="bouton"><i class="fa fa-history"></i> <div class="btn">Back to list</div></div>
<% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">
<h1>Your Tasks</h1>
<div class="todo">
<ul>
  <% @tasks.each do |task| %>
  <li>
  <div>
  <% if task.completed %>
        <i class="fa-regular fa-circle-check"></i>
      <% else %>
    <i class="fa-regular fa-circle"></i>
      <% end %>

    <%# <%= check_box_tag 'activated[]', task.id %>
    <%= link_to task.title, task_path(task) %></div>
    <div><%= link_to "Delete", task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    <i class="fa-solid fa-trash" aria-hidden="true"></i></div>
    </li>
     <% end %>
</ul>
</div>

<hr>
<%= link_to new_task_path do %>
 <div class="bouton"> <i class="fa fa-plus"></i> <div class="btn">Add a new task</div></div>
<% end %>
</div>

app/views/tasks/new.html.erb
<div class="container">
<h1>New task</h1>
<div class="todo">
<%= form_for(@task) do |f| %>
 <div class="form"> <%= f.label :title %>
  <%= f.text_field :title %>
 <div class="form"> <%= f.label :details %>
  <%= f.text_field :details %></div>
  <div class="sub"><%= f.submit %></div>
<% end %>
</div>
</div>
<hr>
<%= link_to tasks_path do %>
  <div class="bouton"><i class="fa fa-history"></i> <div class="btn">Back to list</div></div>
<% end %>

app/views/tasks/show.html.erb
<div class="container">
<%= link_to edit_path(@task.id) do %>
  <div class="bouton1"><div class="btn"><i class="fa fa-pencil"></i>Edit this task</div></div>
<% end %>

<h1><%= @task.title %></h1>
<div class="todo">
<p class="well"><%= @task.details %></p>
<div class="taskok">
<% if @task.completed %>
  <i class="fa-regular fa-circle-check"></i> This task is completed
<% else %>
  <i class="fa-regular fa-circle"></i> This task is not completed yet
<% end %>
</div>
</div>
<hr>
<%= link_to tasks_path do %>
   <div class="bouton"><i class="fa fa-history"></i> <div class="btn">Back to list</div></div>
<% end %>
</div>